export const ADD_EMAIL = "ADD_EMAIL";
export const ADD_PASSWORD = "ADD_PASSWORD";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const ADD_TOKEN = "ADD_TOKEN";
export const NOTIFY = "NOTIFY";
export const LOGOUT = "LOGOUT";
export const LOGOUT_JUDGE = "LOGOUT_JUDGE";
export const UPDATE_USER = "UPDATE_USER";
export const PREV_PAGE = "PREV_PAGE";
export const SCROLL_HANDLE = "SCROLL_HANDLE";

// competition
export const CREATE_OR_UPDATE_COMPETITION = "CREATE_OR_UPDATE_COMPETITION";
export const GET_CATEGORY_AND_SUB_CATEGORY = "GET_CATEGORY_AND_SUB_CATEGORY";
export const SELECT_ASSESSMENT_CRITERIA = "SELECT_ASSESSMENT_CRITERIA";
export const REMOVE_ASSESSMENT_CRITERIA = "REMOVE_ASSESSMENT_CRITERIA";
export const SET_ROUND_STATUS = "SET_ROUND_STATUS";
export const GET_ALL_COMPETITIONS_PARTICIPATED =
  "GET_ALL_COMPETITIONS_PARTICIPATED";
export const GET_ALL_COMPETITIONS_ORGANIZED = "GET_ALL_COMPETITIONS_ORGANIZED";
export const SET_COMPETITION_SELECTED = "SET_COMPETITION_SELECTED";
export const SET_ROUND_SELECTED_PARTICIPATED =
  "SET_ROUND_SELECTED_PARTICIPATED";
export const GET_ALL_ROUNDS_PARTICIPATED = "GET_ALL_ROUNDS_PARTICIPATED";
export const CLEAR_COMPETITION_STATE = "CLEAR_COMPETITION_STATE";
// round
export const GET_ALL_ROUNDS = "GET_ALL_ROUNDS";
export const CREATE_ROUND = "CREATE_ROUND";
export const GET_SINGLE_ROUND = "GET_SINGLE_ROUND";
export const CLEAR_ROUND = "CLEAR_ROUND";
export const DRAG_AND_DROP_ROUNDS = "DRAG_AND_DROP_ROUNDS";

// config
export const PUSH_REQUEST = "PUSH_REQUEST";
export const POP_REQUEST = "POP_REQUEST";
export const PERSIST_COMPETITION = "PERSIST_COMPETITION";
export const CLEAR_PERSIST_CONFIG = "CLEAR_PERSIST_CONFIG";
export const PUSH_UPLOAD_COMPLETED = "PUSH_UPLOAD_COMPLETED";
export const SET_EXCEPTION_OCCURED = "SET_EXCEPTION_OCCURED";
export const ACTIVATE_UPLOAD_REQUEST = "ACTIVATE_UPLOAD_REQUEST";
export const DEACTIVATE_UPLOAD_REQUEST = "DEACTIVATE_UPLOAD_REQUEST";

// containers
export const GET_ALL_CONTAINERS = "GET_ALL_CONTAINERS";
export const SET_CONTAINER_SELECTED_OR_UNSELECTED =
  "SET_CONTAINER_SELECTED_OR_UNSELECTED";
export const SET_CONTAINER_ACTIVE = "SET_CONTAINER_ACTIVE";
export const CRUD_MEMBER_CONTAINER = "CRUD_MEMBER_CONTAINER";
export const UPDATE_CONTAINER_BULK = "UPDATE_CONTAINER_BULK";
export const CREATE_CONTAINER = "CREATE_CONTAINER";
export const REARRANGE_CONTAINERS = "REARRANGE_CONTAINERS";
export const CLEAR_CONTAINERS = "CLEAR_CONTAINERS";
export const SET_SELECTION_FOR_CONTAINERS = "SET_SELECTION_FOR_CONTAINERS";
export const SELECT_CONTAINERS = "SELECT_CONTAINERS";
export const UNSELECT_CONTAINERS = "UNSELECT_CONTAINERS";
export const GET_CONTAINER = "GET_CONTAINER";
export const SET_QUALIFIED_CONTAINERS = "SET_QUALIFIED_CONTAINERS";
export const DRAG_AND_DROP_CONTAINERS = "DRAG_AND_DROP_CONTAINERS";

// rooms
export const GET_ALL_ROOMS = "GET_ALL_ROOMS";
export const SET_ROOM_SELECTED = "SET_ROOM_SELECTED";
export const CREATE_ROOM = "CREATE_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";

// judge scoring
export const GET_ALL_ROUND_CONTAINERS = "GET_ALL_ROUND_CONTAINERS";
export const UPDATE_ROUND_CONTAINER = "UPDATE_ROUND_CONTAINER";
export const ADD_JUDGE_TOKEN = "ADD_JUDGE_TOKEN";
export const ADD_JUDGE_ROUND = "ADD_JUDGE_ROUND";
export const GET_ROUND = "GET_ROUND";
export const CLEAR_JUDGE_STATE = "CLEAR_JUDGE_STATE";

//Misc
export const GET_SUB_PROFESSION = "GET_SUB_PROFESSION";
export const GET_INSTITUTES = "GET_INSTITUTES";
export const CREATE_INSTITUTE = "CREATE_INSTITUTE";
export const UPDATE_JUDGE = "UPDATE_JUDGE";
export const SET_ACTIVE_SETTING_SECTION = "SET_ACTIVE_SETTING_SECTION";
export const INITIALIZE_ANALYTICS = "INITIALIZE_ANALYTICS";

//Chat
export const SET_CONTAINER_SELECTED_CHAT = "SET_CONTAINER_SELECTED_CHAT";
export const GET_CHAT = "GET_CHAT";
export const ADD_GROUP_CHAT = "ADD_GROUP_CHAT";
export const ADD_ORGANISER_CHAT = "ADD_ORGANISER_CHAT";
export const SET_ROOM_SELECTED_CHAT = "SET_ROOM_SELECTED_CHAT";
export const GET_ALL_ROOMS_CHAT = "GET_ALL_ROOMS_CHAT";
export const GET_ALL_CONTAINERS_CHAT = "GET_ALL_CONTAINERS_CHAT";
export const JOIN_ROOM = "JOIN_ROOM";
//Stop loader on API call
export const STOP_LOADER_ON_API = "STOP_LOADER_ON_API";
export const REINITIALIZE_LOADER_ON_API = "REINITIALIZE_LOADER_ON_API";

//Remove Participant global management
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

// persist round category
export const ROUND_CATEGORY = "ROUND_CATEGORY";

// Leaderboard Containers
export const SET_LEADERBOARD_CONTAINERS = "SET_LEADERBOARD_CONTAINERS";

// Paginated Containers List
export const SET_CONTAINERS_LIST = "SET_CONTAINERS_LIST";
export const SET_REGISTRATIONS_LIST = "SET_REGISTRATIONS_LIST";
